########################################## SINGLEVC  ##########################
train_wav_dir: "VCTK-Corpus/wav22050/p249/"
test_wav_dir: "Any2One_Test22050/"
out_dir: "any2one/output/"

local_rank: 1
resume: True
resume_model_path: "model/checkpoint-3000.pt"
epochs: 4000
batch_size: 4

save_period: 50
eval_period: 50
step_record_time: 8

learning_rate: 0.0001
adam_b1: 0.8
adam_b2: 0.99
lr_decay: 0.995
weight_decay: 0.00015

########################################## HIFI-GAN ##########################
hifi_model_path: "hifivoice/pretrained/UNIVERSAL_V1/g_02500000"
hifi_config_path: "hifivoice/pretrained/UNIVERSAL_V1/config.json"

########################################## MEL-FEATURE ##########################
sampling_rate: 22050
num_mels: 80
num_freq: 1025
n_fft: 1024
hop_size: 256
win_size: 1024
fmin: 0
fmax: 8000

num_workers: 1


